//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanAnGiaDinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAn
    {
        public int mabanan { get; set; }
        public string tenbanan { get; set; }
        public string trangthai { get; set; }
    }
}
