//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanAnGiaDinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int mahoadon { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<int> maphieugoimon { get; set; }
        public Nullable<double> tongtien { get; set; }
    }
}
